Cargo.toml, deny.toml, examples/cli-test-direct.sh, examples/cli-test-nested.sh, examples/cli-test-routed.sh, examples/src/cli.rs, tsp/Cargo.toml, tsp/src/async_store.rs, tsp/src/crypto/tsp_hpke.rs, tsp/src/definitions/mod.rs, tsp/src/error.rs, tsp/src/lib.rs, tsp/src/store.rs, tsp/src/vault.rs, tsp/src/vid/deserialize.rs, tsp/src/vid/did/peer.rs, tsp/src/vid/did/web.rs, tsp/src/vid/mod.rs
- Make secret key material more secret (zeroize)
- Add key persistence based on aries-askar
=> Add aries-askar as storage layer

Cargo.toml, examples/src/cli.rs, tsp/Cargo.toml, tsp/src/cesr/packet.rs, tsp/src/test.rs, tsp/src/transport/error.rs, tsp/src/transport/http.rs, tsp/src/transport/mod.rs, tsp/src/transport/quic.rs, tsp/src/transport/tcp.rs, tsp/src/transport/tls.rs, tsp/src/vault.rs, tsp/src/vid/did/web.rs
Quic transport using the `quinn` crate. Based on the rustls transport. This transport scheme is `quic://.....`
=> Quic transport

Cargo.toml, tsp/src/crypto/tsp_hpke.rs
We're not going to create a fork of HPKE, and the original interface suits our code actually quite well.
=> Switch to official hpke

tsp/src/cesr/packet.rs, tsp/src/crypto/tsp_hpke.rs, tsp/src/store.rs, tsp/src/vid/resolve.rs
Also closes issue #7: we had no dependency on access to these fields.
=> Remove and address TODO's

examples/Cargo.toml, examples/cli-test-relations.sh, examples/cli-test-routed-2.sh, examples/src/cli.rs, tsp/src/async_store.rs, tsp/src/error.rs, tsp/src/store.rs, tsp/src/test.rs
This makes everything more testable.
=> CLI Enhancements

tsp/src/async_store.rs, tsp/src/store.rs
=> Micro-optimizations

Cargo.toml, tsp-javascript/Cargo.toml, tsp-python/Cargo.toml, tsp-python/src/lib.rs, tsp/Cargo.toml
Reverts openwallet-foundation-labs/tsp#59
=> Revert "Update dependencies to latest versions."

examples/script.js
=> Automatically reconnect WebSocket

.dockerignore, .github/workflows/deploy.yml, Cargo.toml, Dockerfile, deploy/did-web.template.yaml, deploy/intermediary.template.yaml, deploy/server.template.yaml, docker-compose.yaml, docs/src/SUMMARY.md, docs/src/hosting.md, examples/Cargo.toml, examples/src/cli.rs, examples/src/did-web.rs, examples/src/server.rs, tsp/Cargo.toml, tsp/src/async_store.rs, tsp/src/transport/http.rs, tsp/src/vid/did/peer.rs, tsp/src/vid/did/web.rs
=> Separate DID support and demo server

docs/src/SUMMARY.md, docs/src/cli/installation.md, docs/src/cli/nested.md, docs/src/cli/routed.md, docs/src/cli/usage.md, docs/src/custom-secure-storage.md, docs/src/custom-vids.md, docs/src/intermediary.md, docs/src/sdk-apis.md, docs/src/web-interface.md, examples/cli-demo-doubly-nested.sh, examples/cli-demo-nested.sh, examples/cli-demo-routed-cli-only.sh, examples/cli-demo-routed-external.sh, examples/cli-demo-routed-local.sh, examples/cli-test-cross-type.sh, examples/cli-test-direct.sh, examples/cli-test-nested.sh, examples/src/cli.rs, examples/src/did-web.rs, examples/src/intermediary.rs, examples/src/server.rs, tsp_javascript/src/lib.rs, tsp_python/src/lib.rs, tsp_sdk/Cargo.toml, tsp_sdk/src/async_store.rs, tsp_sdk/src/lib.rs, tsp_sdk/src/secure_storage.rs, tsp_sdk/src/store.rs, tsp_sdk/src/test.rs
- Expose SecureStorage trait with documentation on custom secure storage
- Make it possible to use PostgreSQL instead of SQLite for Aries Askar
- Renamed `Store` to `SecureStore`
- Renamed database to wallet
=> Update Secure Storage API

tsp_sdk/src/store.rs
Based on feedback from #122, make the relationship error more clearly explain what is wrong
=> Improve relationship error messages

Cargo.toml, tsp_sdk/src/async_store.rs, tsp_sdk/src/lib.rs, tsp_sdk/src/store.rs
Related to https://github.com/openwallet-foundation/askar/issues/383 and https://github.com/openwallet-foundation/askar/pull/386
=> Patch `askar` compilation error

docs/src/cli/installation.md, docs/src/cli/usage.md, examples/did-web.html, examples/src/cli.rs, examples/src/did-web.rs
=> Add DID server index page with recently published DIDs 

docs/src/cli/installation.md, docs/src/cli/usage.md, examples/did-web.html, examples/src/cli.rs, examples/src/did-web.rs, tsp_sdk/src/vid/did/mod.rs, tsp_sdk/src/vid/did/web.rs
- Fixes #136 by only publishing the public part
- Prints DID document URL after successful creation
- Better error handling for when a DID cannot be published based on 7b46da04a79232b56340c77bf189f13c49cd27ab (sorry for the merge conflict @pohlm01)
=> Improve tsp create command

.github/workflows/deploy.yml, demo/src/useStore.ts, docs/src/cli/installation.md, docs/src/cli/nested.md, docs/src/cli/usage.md, docs/src/web-interface.md, examples/did-web.html, examples/src/cli.rs, examples/src/did-web.rs, examples/src/server.rs, examples/test/ssl-proxy.json, tsp_sdk/src/secure_storage.rs, tsp_sdk/src/test.rs, tsp_sdk/src/vid/did/web.rs
- Renamed "user" to "endpoint" in DIDs, fixes #121
- Added discovery list to DID support server, improves on #131
- Added `tsp discover` command as suggested by #125
=> DID discovery improvements

tsp_sdk/src/async_store.rs, tsp_sdk/src/store.rs
As suggested by @chengr4, this is a useful method to have
=> Add `has_verified_vid` method and improve `has_private_vid`

examples/src/cli.rs, examples/src/did-server.rs, examples/src/server.rs, tsp_python/src/lib.rs, tsp_sdk/src/async_store.rs, tsp_sdk/src/crypto/mod.rs, tsp_sdk/src/definitions/mod.rs, tsp_sdk/src/secure_storage.rs, tsp_sdk/src/store.rs, tsp_sdk/src/vid/did/webvh.rs
Note: there are also some formatting improvements.
=> Assign default relation when receiving accept relationship

docs/src/cli/nested.md, docs/src/cli/routed.md, docs/src/cli/usage.md, docs/src/intermediary.md, examples/Cargo.toml, examples/src/intermediary.rs, tsp_sdk/src/async_store.rs
=> Intermediary and docs

docs/src/SUMMARY.md, docs/src/tmcp.md
=> Add TMCP documentation

docs/src/python.md
Improve docs based on feedback from Ayu on Discord
=> Python docs improvements

docs/src/cli/nested.md
=> [Doc] Update nested  mode section
